// ─────────────────────────────────────────────────────────────────────────────
// BrainLLM — tamper-evident record seals
//
// Records (sessions, diary entries, dated thread entries) are append-only by
// contract: a block, once written, is history. Nothing checked that. A record
// could be rewritten — by a tool bug, a stray edit, a sync — and every reader
// after it would trust the new text as what happened.
//
// Each close() seals its day. For every record of the day the seal stores the
// length of its readable text and a hash of that text; the day's digest
// chains those entries to the previous sealed day's digest (the idea adopted
// from Oh's digest-chained log, 2026-10-09). The seal lives in labels on the
// day's Insights log note, beside the log rather than in it, because past logs
// are legitimately regenerated by the deletion catch-up.
//
// Verification (maintain(deep)) re-reads each sealed day's records and checks
// three things:
//   1. each record's current text still STARTS with exactly what was sealed —
//      appends after the seal are allowed, because that is what records do;
//   2. the stored record list still hashes to the stored digest;
//   3. each seal's "previous" link equals the previous sealed day's digest.
// A failure is reported, never repaired: the brain cannot know which side is
// true, and the revision history can.
//
// Readable text, not stored HTML, is what is hashed, so the editor
// re-serializing markup on open is not a false alarm.
// ─────────────────────────────────────────────────────────────────────────────

import { createHash } from "node:crypto";
import { type TriliumClient, type Note, ownedLabel } from "./trilium.js";
import type { BrainLLMConfig } from "./config.js";
import { decodeEntities } from "./normalize.js";

const GENESIS = "genesis";

/** A record's text as hashed: tags removed, entities decoded, whitespace
 *  collapsed. Stable under markup re-serialization. */
export function sealText(html: string): string {
  return decodeEntities(html.replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ").trim();
}

export function sha(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

/** noteId → [sealed text length, first 16 hex of the hash of that text]. */
export type SealedRecords = Record<string, [number, string]>;

export function sealRecord(text: string): [number, string] {
  return [text.length, sha(text).slice(0, 16)];
}

/** The day's digest: previous digest, date and the sealed record list, in a
 *  canonical order. */
export function dayDigest(prev: string, date: string, records: SealedRecords): string {
  const canonical = Object.keys(records).sort().map((id) => `${id}:${records[id]![0]}:${records[id]![1]}`).join(",");
  return sha(`${prev}\n${date}\n${canonical}`);
}

/** Whether a record's current text still begins with what was sealed. */
export function recordIntact(current: string, sealed: [number, string]): boolean {
  if (current.length < sealed[0]) return false;
  return sha(current.slice(0, sealed[0])).slice(0, 16) === sealed[1];
}

/** Every record dated `date`: the session note, the diary entry and each
 *  dated thread entry. */
async function dayRecords(trilium: TriliumClient, cfg: BrainLLMConfig, date: string): Promise<Note[]> {
  const find = (ancestor: string | undefined, kind: string) =>
    ancestor
      ? trilium
          .searchNotes(`#noteType=${kind} #created='${date}'`, { ancestorNoteId: ancestor, fastSearch: true, limit: 200, includeArchivedNotes: true })
          .then((r) => r.results)
          .catch(() => [] as Note[])
      : Promise.resolve([] as Note[]);
  const [sessions, diary, entries] = await Promise.all([
    find(cfg.memory.sessions, "session"),
    find(cfg.llm.diary, "diary"),
    find(cfg.memory.threads, "threadEntry"),
  ]);
  return [...sessions, ...diary, ...entries.filter((n) => n.title.trim() === `[${date}]`)];
}

/** Sealed logs, oldest first. */
async function sealedLogs(trilium: TriliumClient, cfg: BrainLLMConfig): Promise<Note[]> {
  if (!cfg.insights.logs) return [];
  const res = await trilium
    .searchNotes("#noteType=log #seal", { ancestorNoteId: cfg.insights.logs, fastSearch: true, limit: 1000, includeArchivedNotes: true })
    .catch(() => ({ results: [] as Note[] }));
  return res.results
    .filter((n) => ownedLabel(n, "seal"))
    .sort((a, b) => (ownedLabel(a, "created") ?? "").localeCompare(ownedLabel(b, "created") ?? ""));
}

export interface SealReport {
  date: string;
  digest: string;
  records: number;
}

/** Seal `date` on its log note. Re-sealing the same day (a second close)
 *  replaces that day's seal and keeps its link to the previous day. */
export async function sealDay(trilium: TriliumClient, cfg: BrainLLMConfig, date: string, logNoteId: string): Promise<SealReport> {
  const earlier = (await sealedLogs(trilium, cfg)).filter((n) => (ownedLabel(n, "created") ?? "") < date);
  const prev = earlier.length ? ownedLabel(earlier[earlier.length - 1]!, "seal")! : GENESIS;
  const records: SealedRecords = {};
  for (const n of await dayRecords(trilium, cfg, date)) {
    const content = await trilium.getNoteContent(n.noteId).catch(() => "");
    if (content) records[n.noteId] = sealRecord(sealText(content));
  }
  const digest = dayDigest(prev, date, records);
  await trilium.updateLabelValue(logNoteId, "sealRecords", JSON.stringify(records));
  await trilium.updateLabelValue(logNoteId, "sealPrev", prev);
  await trilium.updateLabelValue(logNoteId, "seal", digest);
  return { date, digest, records: Object.keys(records).length };
}

export interface SealFinding {
  date: string;
  noteId?: string;
  problem: string;
}

/** Verify the most recent `days` sealed days (today excluded: its records are
 *  still being written and the next close re-seals it). */
export async function verifySeals(trilium: TriliumClient, cfg: BrainLLMConfig, today: string, days = 7): Promise<{ checked: number; findings: SealFinding[] }> {
  const logs = (await sealedLogs(trilium, cfg)).filter((n) => (ownedLabel(n, "created") ?? "") < today);
  const findings: SealFinding[] = [];
  const window = logs.slice(-days);
  for (const log of window) {
    const date = ownedLabel(log, "created") ?? "";
    const digest = ownedLabel(log, "seal") ?? "";
    const prev = ownedLabel(log, "sealPrev") ?? "";
    const i = logs.indexOf(log);
    const expectedPrev = i > 0 ? ownedLabel(logs[i - 1]!, "seal") ?? "" : prev;
    if (prev !== expectedPrev) {
      findings.push({ date, noteId: log.noteId, problem: `the chain breaks here — this seal links to ${prev.slice(0, 12)}…, but the previous sealed day's digest is ${expectedPrev.slice(0, 12)}…` });
    }
    let records: SealedRecords;
    try {
      records = JSON.parse(ownedLabel(log, "sealRecords") ?? "{}") as SealedRecords;
    } catch {
      findings.push({ date, noteId: log.noteId, problem: "the sealed record list is unreadable" });
      continue;
    }
    if (dayDigest(prev, date, records) !== digest) {
      findings.push({ date, noteId: log.noteId, problem: "the sealed record list no longer matches its digest — the seal labels were edited" });
    }
    for (const [noteId, sealed] of Object.entries(records)) {
      const content = await trilium.getNoteContent(noteId).catch(() => null);
      if (content === null) {
        findings.push({ date, noteId, problem: "a sealed record is gone (deleted or unreadable)" });
        continue;
      }
      if (!recordIntact(sealText(content), sealed)) {
        findings.push({ date, noteId, problem: "a sealed record was changed after its day was sealed — its sealed text is no longer the start of its body. diff(noteId) and the note's revisions show what changed" });
      }
    }
  }
  return { checked: window.length, findings };
}
